/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/files/upload": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post: operations["postFilesUpload"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/todo": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getTodo"];
        readonly put?: never;
        readonly post: operations["postTodo"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/todo/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get: operations["getTodoById"];
        readonly put: operations["putTodoById"];
        readonly post?: never;
        readonly delete: operations["deleteTodoById"];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly postFilesUpload: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    /**
                     * Format: binary
                     * @default File
                     */
                    readonly file: string;
                };
                readonly "multipart/form-data": {
                    /**
                     * Format: binary
                     * @default File
                     */
                    readonly file: string;
                };
                readonly "text/plain": {
                    /**
                     * Format: binary
                     * @default File
                     */
                    readonly file: string;
                };
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly success: boolean;
                        readonly path: string;
                        readonly id: string;
                    };
                    readonly "multipart/form-data": {
                        readonly success: boolean;
                        readonly path: string;
                        readonly id: string;
                    };
                    readonly "text/plain": {
                        readonly success: boolean;
                        readonly path: string;
                        readonly id: string;
                    };
                };
            };
        };
    };
    readonly getTodo: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": readonly {
                        readonly id: string;
                        readonly title: string;
                        readonly completed: boolean;
                    }[];
                    readonly "multipart/form-data": readonly {
                        readonly id: string;
                        readonly title: string;
                        readonly completed: boolean;
                    }[];
                    readonly "text/plain": readonly {
                        readonly id: string;
                        readonly title: string;
                        readonly completed: boolean;
                    }[];
                };
            };
        };
    };
    readonly postTodo: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly id: string;
                    readonly title: string;
                    readonly completed: boolean;
                };
                readonly "multipart/form-data": {
                    readonly id: string;
                    readonly title: string;
                    readonly completed: boolean;
                };
                readonly "text/plain": {
                    readonly id: string;
                    readonly title: string;
                    readonly completed: boolean;
                };
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": {
                        readonly id: string;
                        readonly title: string;
                        readonly completed: boolean;
                    };
                    readonly "multipart/form-data": {
                        readonly id: string;
                        readonly title: string;
                        readonly completed: boolean;
                    };
                    readonly "text/plain": {
                        readonly id: string;
                        readonly title: string;
                        readonly completed: boolean;
                    };
                };
            };
        };
    };
    readonly getTodoById: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly putTodoById: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": {
                    readonly id: string;
                    readonly title: string;
                    readonly completed: boolean;
                };
                readonly "multipart/form-data": {
                    readonly id: string;
                    readonly title: string;
                    readonly completed: boolean;
                };
                readonly "text/plain": {
                    readonly id: string;
                    readonly title: string;
                    readonly completed: boolean;
                };
            };
        };
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    readonly deleteTodoById: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
export enum ApiPaths {
    postFilesUpload = "/files/upload",
    getTodo = "/todo",
    postTodo = "/todo",
    getTodoById = "/todo/:id",
    putTodoById = "/todo/:id",
    deleteTodoById = "/todo/:id"
}
